---
# tasks file for drush

#drush_install_path: /usr/local/share/drush
#drush_path: /usr/local/bin/drush
#drush_version: master
#drush_keep_updated: no
#drush_force_update: no

-   name: Clone Drush
    git:
        repo: https://github.com/drush-ops/drush.git
        dest: /usr/local/share/drush
        version: master
    register: drush_clone


-   name: Check for composer.json
    stat: path=/usr/local/share/drush/composer.json
    register: drush_composer


-   name: Install dependencies
    shell: >
        /usr/local/bin/composer install
        chdir=/usr/local/share/drush
    when: drush_clone.changed and drush_composer.stat.exists


-   name: Create symlink
    file:
        src: /usr/local/share/drush/drush
        dest: /usr/local/bin/drush
        state: link


-   name: Finish installation
    command: /usr/local/bin/drush
    register: drush_result
    changed_when: "'Execute a drush command' not in drush_result.stdout"
