---
# tasks file for mysql

-   name: Install MySQL
    apt:
        pkg: "{{item}}"
        update_cache: yes
        cache_valid_time: 3600
        state: present
    with_items:
        - python-mysqldb
        - mysql-server-5.5
        - mysql-server

-   name: Start MySQL
    service:
        name: mysql
        state: started
        enabled: true

-   name: Update MySQL root password
    mysql_user: 
        name: root 
        host: "{{ item }}" 
        password: "{{ mysql_root_password }}"
        login_user: root
        login_password: "{{ mysql_root_password }}"
        check_implicit_admin: yes
        priv: "*.*:ALL,GRANT"
    with_items:
        - "{{ ansible_hostname }}"
        - 127.0.0.1
        - ::1
        - localhost 
